version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hypea-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-hypea_root_pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hypea_platform}
      MYSQL_USER: ${MYSQL_USER:-hypea_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-hypea_user_pass}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - hypea-network
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: hypea-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hypea-network
    command: redis-server --appendonly yes

  # Hypea Platform Application
  app:
    build: .
    container_name: hypea-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER:-hypea_user}:${MYSQL_PASSWORD:-hypea_user_pass}@mysql:3306/${MYSQL_DATABASE:-hypea_platform}
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./logs:/app/logs
    networks:
      - hypea-network
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hypea-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    networks:
      - hypea-network
    depends_on:
      - app

volumes:
  mysql_data:
  redis_data:

networks:
  hypea-network:
    driver: bridge
